# Load Environments

## High Performance Computing Cluster

```{bash,eval=F}
cd mamba_environments
for i in *;do mamba env create -f $i;done
```

## Unzipping gzipped datasets

```{bash eval=F}
gunzip data/C_auris_RNA-seq-systematic-review.csv
```

## R Environments for Analysis and Plotting

```{r}
# Data
require(tidyverse)
require(readxl)
require(janitor)
require(kableExtra) 
require(string)

# Statistics
require(scales)
require(ggsignif)
require(growthcurver)
require(survival)
require(survminer)
require(ggfortify)

# Plotting
require(ggprism)
require(ggsci)
require(ggbeeswarm)
require(ggrepel)
require(ComplexHeatmap)
require(tidyHeatmap)
require(patchwork)
require(viridis)
require(circlize)
require(scales)
require(ggnewscale)

# Phylogeny
require(ggtree)
require(TDbook)
require(treeio)
require(phangorn)
require(ggtreeExtra)

# Network
library(igraph)
library(ggraph)
library(ggplot2)
library(reshape2)

my_theme <- theme_minimal() +
  theme(text=element_text(family = "Arial",size=12,colour="black"), #
        panel.grid = element_blank(),
        axis.text= element_text(colour="black"),
        axis.line = element_line(color = "black", size = 0.5),
        plot.title = element_text(hjust = 0.5))
```

R version 4.4.0 (2024-04-24)
Platform: x86_64-apple-darwin20
Running under: macOS Ventura 13.4.1

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib 
LAPACK: /Library/Frameworks/R.framework/Versions/4.4-x86_64/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.0

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

time zone: Africa/Johannesburg
tzcode source: internal

attached base packages:
[1] grid      stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] reshape2_1.4.4        ggraph_2.2.1          igraph_2.0.3          ggtreeExtra_1.14.0    phangorn_2.11.1      
 [6] ape_5.8               treeio_1.28.0         TDbook_0.0.6          ggtree_3.12.0         ggnewscale_0.5.0     
[11] circlize_0.4.16       viridis_0.6.5         viridisLite_0.4.2     patchwork_1.2.0       tidyHeatmap_1.8.1    
[16] ComplexHeatmap_2.20.0 ggrepel_0.9.5         ggbeeswarm_0.7.2      ggsci_3.2.0           ggprism_1.0.5        
[21] ggfortify_0.4.17      survminer_0.4.9       ggpubr_0.6.0          survival_3.7-0        growthcurver_0.3.1   
[26] ggsignif_0.6.4        scales_1.3.0          kableExtra_1.4.0      janitor_2.2.0         readxl_1.4.3         
[31] lubridate_1.9.3       forcats_1.0.0         stringr_1.5.1         dplyr_1.1.4           purrr_1.0.2          
[36] readr_2.1.5           tidyr_1.3.1           tibble_3.2.1          ggplot2_3.5.1         tidyverse_2.0.0      

loaded via a namespace (and not attached):
 [1] RColorBrewer_1.1-3  rstudioapi_0.16.0   jsonlite_1.8.8      shape_1.4.6.1       magrittr_2.0.3     
 [6] farver_2.1.2        rmarkdown_2.28      GlobalOptions_0.1.2 fs_1.6.4            vctrs_0.6.5        
[11] memoise_2.0.1       rstatix_0.7.2       htmltools_0.5.8.1   broom_1.0.6         cellranger_1.1.0   
[16] gridGraphics_0.5-1  plyr_1.8.9          cachem_1.1.0        zoo_1.8-12          lifecycle_1.0.4    
[21] iterators_1.0.14    pkgconfig_2.0.3     Matrix_1.7-0        R6_2.5.1            fastmap_1.2.0      
[26] snakecase_0.11.1    clue_0.3-65         digest_0.6.37       aplot_0.2.3         colorspace_2.1-1   
[31] S4Vectors_0.42.1    fansi_1.0.6         km.ci_0.5-6         timechange_0.3.0    polyclip_1.10-7    
[36] abind_1.4-5         compiler_4.4.0      withr_3.0.1         doParallel_1.0.17   backports_1.5.0    
[41] carData_3.0-5       dendextend_1.17.1   ggforce_0.4.2       MASS_7.3-61         rjson_0.2.22       
[46] tools_4.4.0         vipor_0.4.7         beeswarm_0.4.0      quadprog_1.5-8      glue_1.7.0         
[51] nlme_3.1-166        cluster_2.1.6       generics_0.1.3      gtable_0.3.5        tzdb_0.4.0         
[56] KMsurv_0.1-5        data.table_1.16.0   hms_1.1.3           tidygraph_1.3.1     xml2_1.3.6         
[61] car_3.1-2           utf8_1.2.4          BiocGenerics_0.50.0 foreach_1.5.2       pillar_1.9.0       
[66] yulab.utils_0.1.7   splines_4.4.0       tweenr_2.0.3        lattice_0.22-6      tidyselect_1.2.1   
[71] knitr_1.48          gridExtra_2.3       IRanges_2.38.1      svglite_2.1.3       stats4_4.4.0       
[76] xfun_0.47           graphlayouts_1.1.1  matrixStats_1.3.0   stringi_1.8.4       lazyeval_0.2.2     
[81] ggfun_0.1.6         evaluate_0.24.0     codetools_0.2-20    ggplotify_0.1.2     cli_3.6.3          
[86] xtable_1.8-4        systemfonts_1.1.0   munsell_0.5.1       survMisc_0.5.6      Rcpp_1.0.13        
[91] png_0.1-8           parallel_4.4.0      tidytree_0.4.6      crayon_1.5.3        GetoptLong_1.0.5   
[96] rlang_1.1.4         fastmatch_1.1-4    
